//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPractFinal.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clientes", Namespace="http://schemas.datacontract.org/2004/07/ServiceExamen")]
    [System.SerializableAttribute()]
    public partial class clientes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrepaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcliente {
            get {
                return this.idclienteField;
            }
            set {
                if ((object.ReferenceEquals(this.idclienteField, value) != true)) {
                    this.idclienteField = value;
                    this.RaisePropertyChanged("idcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idpaisField, value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrecia {
            get {
                return this.nombreciaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreciaField, value) != true)) {
                    this.nombreciaField = value;
                    this.RaisePropertyChanged("nombrecia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrepais {
            get {
                return this.nombrepaisField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrepaisField, value) != true)) {
                    this.nombrepaisField = value;
                    this.RaisePropertyChanged("nombrepais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="paises", Namespace="http://schemas.datacontract.org/2004/07/ServiceExamen")]
    [System.SerializableAttribute()]
    public partial class paises : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idpaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombrepaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idpais {
            get {
                return this.idpaisField;
            }
            set {
                if ((object.ReferenceEquals(this.idpaisField, value) != true)) {
                    this.idpaisField = value;
                    this.RaisePropertyChanged("idpais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombrepais {
            get {
                return this.nombrepaisField;
            }
            set {
                if ((object.ReferenceEquals(this.nombrepaisField, value) != true)) {
                    this.nombrepaisField = value;
                    this.RaisePropertyChanged("nombrepais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listaClientes", ReplyAction="http://tempuri.org/IService1/listaClientesResponse")]
        WebPractFinal.ServiceReference1.clientes[] listaClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listaClientes", ReplyAction="http://tempuri.org/IService1/listaClientesResponse")]
        System.Threading.Tasks.Task<WebPractFinal.ServiceReference1.clientes[]> listaClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listaPaises", ReplyAction="http://tempuri.org/IService1/listaPaisesResponse")]
        WebPractFinal.ServiceReference1.paises[] listaPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listaPaises", ReplyAction="http://tempuri.org/IService1/listaPaisesResponse")]
        System.Threading.Tasks.Task<WebPractFinal.ServiceReference1.paises[]> listaPaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCliente", ReplyAction="http://tempuri.org/IService1/AgregarClienteResponse")]
        string AgregarCliente(WebPractFinal.ServiceReference1.clientes reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AgregarCliente", ReplyAction="http://tempuri.org/IService1/AgregarClienteResponse")]
        System.Threading.Tasks.Task<string> AgregarClienteAsync(WebPractFinal.ServiceReference1.clientes reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCliente", ReplyAction="http://tempuri.org/IService1/EliminarClienteResponse")]
        string EliminarCliente(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarCliente", ReplyAction="http://tempuri.org/IService1/EliminarClienteResponse")]
        System.Threading.Tasks.Task<string> EliminarClienteAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebPractFinal.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebPractFinal.ServiceReference1.IService1>, WebPractFinal.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebPractFinal.ServiceReference1.clientes[] listaClientes() {
            return base.Channel.listaClientes();
        }
        
        public System.Threading.Tasks.Task<WebPractFinal.ServiceReference1.clientes[]> listaClientesAsync() {
            return base.Channel.listaClientesAsync();
        }
        
        public WebPractFinal.ServiceReference1.paises[] listaPaises() {
            return base.Channel.listaPaises();
        }
        
        public System.Threading.Tasks.Task<WebPractFinal.ServiceReference1.paises[]> listaPaisesAsync() {
            return base.Channel.listaPaisesAsync();
        }
        
        public string AgregarCliente(WebPractFinal.ServiceReference1.clientes reg) {
            return base.Channel.AgregarCliente(reg);
        }
        
        public System.Threading.Tasks.Task<string> AgregarClienteAsync(WebPractFinal.ServiceReference1.clientes reg) {
            return base.Channel.AgregarClienteAsync(reg);
        }
        
        public string EliminarCliente(string id) {
            return base.Channel.EliminarCliente(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarClienteAsync(string id) {
            return base.Channel.EliminarClienteAsync(id);
        }
    }
}
